version: '2'
services:
  web:
    build: .
    command: npm run start
    networks:
      - mern-stack-net
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:5000"
    depends_on:
      - db
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=password
  db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=todo
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    depends_on:
      - db
    ports:
      - 8080:8081
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local